// DO NOT EDIT! generated by ./autogen

#ifndef primes_h
#define primes_h

#include "primes_namespace.h"

#if BITS == 511 // csidh
#define primes_num 74
#define secret_key_size 74
#define primes_batches 14
#define primes_maxbatchboundplussize 26
#elif BITS == 512 // csurf
#define primes_num 73
#define secret_key_size 74
#define primes_batches 14
#define primes_maxbatchboundplussize 26
#elif BITS == 513 // csurf
#define primes_num 74
#define secret_key_size 75
#define primes_batches 14
#define primes_maxbatchboundplussize 26
#else
#error BITS must be 511 or 512 or 513
#endif

extern const long long primes[primes_num];
extern const long long primes_dac[primes_num];
extern const long long primes_daclen[primes_num];
extern const long long primes_batchsize[primes_batches];
extern const long long primes_batchstart[primes_batches];
extern const long long primes_batchstop[primes_batches];
extern const long long primes_batchbound[primes_batches];
extern const long long primes_batchmaxdaclen[primes_batches];

#endif
